---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 通过将 Astra Trident 与适用于 NetApp ONTAP 的 Amazon FSx 结合使用，您可以确保在 Amazon Elastic Kubernetes Service （ EKS ）中运行的 Kubernetes 集群可以配置由 ONTAP 提供支持的块和文件永久性卷。 
---
= 将 Astra Trident 与适用于 NetApp ONTAP 的 Amazon FSX 结合使用
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["适用于 NetApp ONTAP 的 Amazon FSX"^]是一种完全受管的 AWS 服务，支持客户启动和运行由 NetApp 的 ONTAP 存储操作系统提供支持的文件系统。Amazon FSX for NetApp ONTAP 支持您利用您熟悉的 NetApp 功能，性能和管理功能，同时利用在 AWS 上存储数据的简便性，灵活性，安全性和可扩展性。FSX 支持 ONTAP 的许多文件系统功能和管理 API 。

文件系统是 Amazon FSX 中的主要资源，类似于内部部署的 ONTAP 集群。在每个 SVM 中，您可以创建一个或多个卷，这些卷是将文件和文件夹存储在文件系统中的数据容器。借助适用于 NetApp ONTAP 的 Amazon FSX ， Data ONTAP 将作为云中的托管文件系统提供。新的文件系统类型称为 * NetApp ONTAP * 。

通过将 Astra Trident 与适用于 NetApp ONTAP 的 Amazon FSx 结合使用，您可以确保在 Amazon Elastic Kubernetes Service （ EKS ）中运行的 Kubernetes 集群可以配置由 ONTAP 提供支持的块和文件永久性卷。



== 了解 Astra Trident

如果您是 Astra Trident 的新用户，请使用下面提供的链接进行熟悉：

* link:../faq.html["常见问题解答"^]
* link:../trident-get-started/requirements.html["使用 Astra Trident 的要求"^]
* link:../trident-get-started/kubernetes-deploy.html["部署 Astra Trident"^]
* link:../trident-reco/storage-config-best-practices.html["配置适用于 NetApp ONTAP 的 ONTAP ， Cloud Volumes ONTAP 和 Amazon FSX 的最佳实践"^]
* link:../trident-reco/integrate-trident.html#ontap["集成 Astra Trident"^]
* link:ontap-san.html["ONTAP SAN 后端配置"^]
* link:ontap-nas.html["ONTAP NAS 后端配置"^]


详细了解驱动程序功能 link:../trident-concepts/ontap-drivers.html["此处"^]。

适用于 NetApp ONTAP 的 Amazon FSX 使用 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mgng-stor-tier-fp/GUID-5A78F93F-7539-4840-AB0B-4A6E3252CF84.html["FabricPool"^] 以管理存储层。通过它，您可以根据数据是否经常访问来将数据存储在层中。

Astra Trident希望以ONTAP 或SVM管理员身份使用集群运行 `fsxadmin` 用户或 `vsadmin` SVM用户或具有相同角色的其他名称的用户。。 `fsxadmin` 用户是的有限替换项 `admin` 集群用户。Astra Trident通常使用 `admin` 适用于非Amazon FSX for ONTAP 部署的集群用户。



=== 驱动程序

您可以使用以下驱动程序将 Astra Trident 与适用于 NetApp ONTAP 的 Amazon FSx 集成：

* `ontap-san`：配置的每个PV都是其自己的Amazon FSX for NetApp ONTAP 卷中的一个LUN。
* `ontap-san-economy`：配置的每个PV都是一个LUN、对于NetApp ONTAP 卷、每个Amazon FSX的LUN数量是可配置的。
* `ontap-nas`：配置的每个PV都是一个适用于NetApp ONTAP 的完整Amazon FSX卷。
* `ontap-nas-economy`：配置的每个PV都是一个qtree、对于NetApp ONTAP 卷、每个Amazon FSX的qtree数量是可配置的。
* `ontap-nas-flexgroup`：配置的每个PV都是一个适用于NetApp ONTAP FlexGroup 的完整Amazon FSX卷。




=== 身份验证

Astra Trident 提供两种身份验证模式：

* 基于凭据：您可以使用 `fsxadmin` 文件系统或的用户 `vsadmin` 为SVM配置的用户。我们建议使用 `vsadmin` 用户配置后端。Astra Trident 将使用此用户名和密码与 FSX 文件系统进行通信。
* 基于证书： Astra Trident 将使用 SVM 上安装的证书与 FSX 文件系统上的 SVM 进行通信。


要了解有关身份验证的详细信息，请参见以下链接：

* link:ontap-nas-prep.html["ONTAP NAS"^]
* link:ontap-san-prep.html["ONTAP SAN"^]




== 使用适用于 NetApp ONTAP 的 Amazon FSX 在 EKS 上部署和配置 Astra Trident

.您需要的内容
* 具有的现有Amazon EKS集群或自管理Kubernetes集群 `kubectl` 已安装。
* 可从集群的工作节点访问的适用于 NetApp ONTAP 文件系统和 Storage Virtual Machine （ SVM ）的现有 Amazon FSX 。
* 为准备工作的工作节点 link:worker-node-prep.html["NFS 和 / 或 iSCSI"^]。
+

NOTE: 确保按照 Amazon Linux 和 Ubuntu 所需的节点准备步骤进行操作 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Amazon Machine 映像"^] （ AMIS ），具体取决于您的 EKS AMI 类型。



有关其他 Astra Trident 要求，请参见 link:../trident-get-started/requirements.html["此处"^]。

.步骤
. 使用 ./trident 部署 Astra Trident 。 Get-started/Kubernetes 部署 .html[ 部署方法^ ] 之一部署 Astra Trident 。
. 按照以下步骤配置 Astra Trident ：
+
.. 收集 SVM 的管理 LIF DNS 名称。例如、使用AWS命令行界面查找 `DNSName` 下的条目 `Endpoints` -> `Management` 运行以下命令后：
+
[listing]
----
aws fsx describe-storage-virtual-machines --region <file system region>
----


. 创建并安装用于身份验证的证书。如果您使用的是 `ontap-san` 后端、请参见 link:ontap-san.html["此处"^]。如果您使用的是 `ontap-nas` 后端、请参见 link:ontap-nas.html["此处"^]。
+

NOTE: 您可以从可以访问文件系统的任何位置使用 SSH 登录到文件系统（例如，安装证书）。使用 `fsxadmin` 用户、创建文件系统时配置的密码以及中的管理DNS名称 `aws fsx describe-file-systems`。

. 使用您的证书和管理 LIF 的 DNS 名称创建后端文件，如以下示例所示：
+
[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "backendName": "customBackendName",
  "managementLIF": "svm-XXXXXXXXXXXXXXXXX.fs-XXXXXXXXXXXXXXXXX.fsx.us-east-2.aws.internal",
  "svm": "svm01",
  "clientCertificate": "ZXR0ZXJwYXB...ICMgJ3BhcGVyc2",
  "clientPrivateKey": "vciwKIyAgZG...0cnksIGRlc2NyaX",
  "trustedCACertificate": "zcyBbaG...b3Igb3duIGNsYXNz",
 }
----


有关创建后端的信息，请参见以下链接：

* link:ontap-nas.html["使用 ONTAP NAS 驱动程序配置后端"^]
* link:ontap-san.html["使用 ONTAP SAN 驱动程序配置后端"^]



NOTE: 请勿指定 `dataLIF` 。 `ontap-san` 和 `ontap-san-economy` 支持Astra Trident使用多路径的驱动程序。


WARNING: 在将适用于NetApp ONTAP 的Amazon FSx与Astra Trident结合使用时、会显示 `limitAggregateUsage` 参数不适用于 `vsadmin` 和 `fsxadmin` 用户帐户。如果指定此参数，配置操作将失败。

部署完成后，执行以下步骤以创建 link:../trident-get-started/kubernetes-postdeployment.html["存储类，配置卷以及将卷挂载到 Pod 中"^]。



== 了解更多信息

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 文档"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["有关适用于 NetApp ONTAP 的 Amazon FSX 的博客文章"^]

