---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator 
summary: '使用Trident操作员可以使用中的属性自定义Astra Trident的安装方式 `TridentOrchestrator` 规格' 
---
= 自定义 Trident 操作员部署
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


通过Trident操作符、您可以使用中的属性自定义Astra Trident的安装方式 `TridentOrchestrator` 规格

有关属性列表，请参见下表：

[cols="3"]
|===
| 参数 | Description | Default 


| `namespace` | 用于安装 Astra Trident 的命名空间 | default 


| `debug` | 为 Astra Trident 启用调试 | false 


| `IPv6` | 安装基于 IPv6 的 Astra Trident | false 


| `k8sTimeout` | Kubernetes 操作超时 | 30 秒 


| `silenceAutosupport` | 不要自动向 NetApp 发送 AutoSupport 捆绑包 | false 


| `enableNodePrep` | 自动管理工作节点依赖关系（ * 测试版 * ） | false 


| `autosupportImage` | AutoSupport 遥测的容器映像 | "NetApp/trident autosupport ： 21.04.0" 


| `autosupportProxy` | 用于发送 AutoSupport 遥测的代理的地址 / 端口 | "http://proxy.example.com:8888"[] 


| `uninstall` | 用于卸载 Astra Trident 的标志 | false 


| `logFormat` | 要使用的 Astra Trident 日志记录格式 [text ， json] | 文本 


| `tridentImage` | 要安装的 Astra Trident 映像 | "NetApp/Trident ： 21.04" 


| `imageRegistry` | 内部注册表的路径、格式
`<registry FQDN>[:port][/subpath]` | "K8s.gcr.io/SIG-storage （ K8s 1.17+ ）或 quay.io/k8scsi " 


| `kubeletDir` | 主机上的 kubelet 目录的路径 | "/var/lib/kubelet" 


| `wipeout` | 要删除以执行 Astra Trident 完全删除的资源列表 |  


| `imagePullSecrets` | 从内部注册表中提取映像的机密信息 |  
|===

IMPORTANT: `spec.namespace` 在中指定 `TridentOrchestrator` 表示安装在哪个命名空间Astra Trident中。此参数 * 安装 Astra Trident 后无法更新 * 。如果尝试执行此操作、则会导致状态为 `TridentOrchestrator` 更改为 `Failed`。Astra Trident 不适用于跨命名空间迁移。


NOTE: 自动员工节点准备是一项 * 测试版功能 * ，仅用于非生产环境。

您可以在定义时使用上述属性 `TridentOrchestrator` 自定义安装。以下是一个示例：

[listing]
----
$ cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  tridentImage: netapp/trident:21.04.0
  imagePullSecrets:
  - thisisasecret
----
如果您希望对安装进行自定义 `TridentOrchestrator` 参数允许、您应考虑使用 `tridentctl` 生成可根据需要修改的自定义YAML清单。
